export const cardAssets = {
  "FRAME_LM": "assets/minigames/cards/FRAME_LM.png",
  "FRAME_UM": "assets/minigames/cards/FRAME_UM.png",
  "FRAME_EFFECT": "assets/minigames/cards/FRAME_EFFECT.png",
  "CHAMPION_CARD_BACK": "assets/minigames/cards/CHAMPION_CARD_BACK.png",
  "CARD_BATTLEFIELD_TAVERN": "assets/minigames/cards/CARD_BATTLEFIELD_TAVERN.png",
  "DARK_SPECIAL_FULL": "assets/minigames/cards/DARK_SPECIAL_FULL.png",
  "CE001": "assets/minigames/cards/CE001.png",
  "CE002": "assets/minigames/cards/CE002.png",
  "CE003": "assets/minigames/cards/CE003.png",
  "CE004": "assets/minigames/cards/CE004.png",
  "CE005": "assets/minigames/cards/CE005.png",
  "IE001": "assets/minigames/cards/IE001.png",
  "IE002": "assets/minigames/cards/IE002.png",
  "IE003": "assets/minigames/cards/IE003.png",
  "IE004": "assets/minigames/cards/IE004.png",
  "IE005": "assets/minigames/cards/IE005.png",
  "IE006": "assets/minigames/cards/IE006.png",
  "IE007": "assets/minigames/cards/IE007.png",
  "IE008": "assets/minigames/cards/IE008.png",
  "IE009": "assets/minigames/cards/IE009.png",
  "IE010": "assets/minigames/cards/IE010.png",
  "LM001": "assets/minigames/cards/LM001.png",
  "LM002": "assets/minigames/cards/LM002.png",
  "LM003": "assets/minigames/cards/LM003.png",
  "LM004": "assets/minigames/cards/LM004.png",
  "LM005": "assets/minigames/cards/LM005.png",
  "LM006": "assets/minigames/cards/LM006.png",
  "LM007": "assets/minigames/cards/LM007.png",
  "LM008": "assets/minigames/cards/LM008.png",
  "LM009": "assets/minigames/cards/LM009.png",
  "LM010": "assets/minigames/cards/LM010.png",
  "LM011": "assets/minigames/cards/LM011.png",
  "LM012": "assets/minigames/cards/LM012.png",
  "LM013": "assets/minigames/cards/LM013.png",
  "LM014": "assets/minigames/cards/LM014.png",
  "UM001": "assets/minigames/cards/UM001.png",
  "UM002": "assets/minigames/cards/UM002.png",
  "UM003": "assets/minigames/cards/UM003.png",
  "UM004": "assets/minigames/cards/UM004.png",
  "SP001": "assets/minigames/cards/SP001.png",
  "SP002": "assets/minigames/cards/SP002.png",
  "SP003": "assets/minigames/cards/SP003.png"
};
import {imageURL} from '../../services/image-source.js';
export const cardAssetURL = id => cardAssets[id] ? imageURL(cardAssets[id]) : null;
