// Exact v0.2 section 13 wording; one definition per global ID.
export const definitions = {
  "CE001": {
    "cardId": "CE001",
    "nameZh": "糞坑",
    "type": "CE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "我方怪物持續 +1 ATK/+0 HP；敵方怪物持續 +0 ATK/-1 HP。敵方 -1 HP 不是傷害，不觸發傷害反應，且不能把怪物降到 1 HP 以下。對已在場與後續進場怪皆適用。此卡離場時，所有由此卡提供的持續數值修正立即取消。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "CE001",
    "frameType": "EFFECT"
  },
  "CE002": {
    "cardId": "CE002",
    "nameZh": "溪流",
    "type": "CE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "我方怪物持續 +1 ATK/+1 HP；已在場與後續進場皆適用。此卡離場時立刻取消；若移除 +1 HP 後某怪 HP 變為 0，該怪立即死亡並可觸發遺言。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "CE002",
    "frameType": "EFFECT"
  },
  "CE003": {
    "cardId": "CE003",
    "nameZh": "黃金殿",
    "type": "CE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "我方全體持續 +1/+1。自打出後的下一輪開始，每次 Round Start 選擇 1 名我方怪物永久 +1/+1；若當下沒有我方怪物，本次成長落空。此卡離場只取消全體持續 +1/+1；過去累積的永久 +1/+1 保留。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "CE003",
    "frameType": "EFFECT"
  },
  "CE004": {
    "cardId": "CE004",
    "nameZh": "下水道",
    "type": "CE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "我方全體持續 +0/+1。每次 Round Start 選擇 1 名我方怪永久 +1/+1，並選擇 1 名敵方怪永久 +0/+1。離場只取消全體持續 +0/+1；個別永久成長保留。目標選擇細則仍需最終鎖定。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "CE004",
    "frameType": "EFFECT"
  },
  "CE005": {
    "cardId": "CE005",
    "nameZh": "坐式馬桶",
    "type": "CE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "每次 Round Start，隨機 1 名存活我方怪物獲得護盾 1；護盾於輪末清除。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "CE005",
    "frameType": "EFFECT"
  },
  "IE001": {
    "cardId": "IE001",
    "nameZh": "局部湮滅",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "指定 1 名當下實際 HP≤5 的敵方怪物，直接令其死亡。護盾不計入 HP 門檻。這不是傷害，不觸發反擊；死亡正常觸發遺言。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE001",
    "frameType": "EFFECT"
  },
  "IE002": {
    "cardId": "IE002",
    "nameZh": "大湮滅",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "敵我雙方所有怪物直接死亡，雙方常駐效果卡同時離場。死亡不是傷害，不觸發反擊；所有應觸發的遺言正常處理。常駐持續修正於離場瞬間取消。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE002",
    "frameType": "EFFECT"
  },
  "IE003": {
    "cardId": "IE003",
    "nameZh": "屎彈",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "二選一：A. 指定怪物造成 2 點傷害；此傷害可觸發反擊。B. 指定一張場上的常駐效果卡，令其立即離場並取消其持續效果。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE003",
    "frameType": "EFFECT"
  },
  "IE004": {
    "cardId": "IE004",
    "nameZh": "冰彈",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "指定 1 名怪物，本輪冰凍：不能行動／不能處理自身效果，但仍可被攻擊。輪末若存活則解除冰凍。",
    "deckRefs": "決鬥×1／冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE004",
    "frameType": "EFFECT"
  },
  "IE005": {
    "cardId": "IE005",
    "nameZh": "局部轉移",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "將 1 名我方怪物移動至另一個空的我方怪物格。保留當前數值、永久修正與狀態。",
    "deckRefs": "決鬥×1／冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE005",
    "frameType": "EFFECT"
  },
  "IE006": {
    "cardId": "IE006",
    "nameZh": "星象轉移",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "指定 1 名敵方怪物，移入任一空的我方怪物格並取得控制權。必須存在我方空格。保留當前 ATK/HP、永久修正、護盾、燃燒、冰凍與一次性能力已使用紀錄；控制權改變不重置能力。之後左右／正前方依新控制者 owner-local 視角重算，且常駐效果依新陣營重新套用。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE006",
    "frameType": "EFFECT"
  },
  "IE007": {
    "cardId": "IE007",
    "nameZh": "順風",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "先抽 1 張，之後敵方隨機棄 1 張手牌。若敵方沒有手牌，只有抽牌效果。抽牌須走逐張進手／特殊勝利／手牌上限流程。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE007",
    "frameType": "EFFECT"
  },
  "IE008": {
    "cardId": "IE008",
    "nameZh": "夜壺",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "抽 2 張。逐張處理每一次進手、黑暗大法屎檢查與超額棄牌。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE008",
    "frameType": "EFFECT"
  },
  "IE009": {
    "cardId": "IE009",
    "nameZh": "天屎的施捨",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "抽 2 張，再自行選擇棄 1 張。抽 2 的過程仍逐張套用通用手牌上限流程；之後再執行卡片本身的額外「棄 1」。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE009",
    "frameType": "EFFECT"
  },
  "IE010": {
    "cardId": "IE010",
    "nameZh": "緊急防護",
    "type": "IE",
    "baseAtk": null,
    "baseHp": null,
    "effectText": "指定 1 名我方怪物立即獲得護盾 2。護盾不增加實際 HP，因此不改變 IE001 局部湮滅的 HP 門檻判定。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "IE010",
    "frameType": "EFFECT"
  },
  "LM001": {
    "cardId": "LM001",
    "nameZh": "小屎塊",
    "type": "LM",
    "baseAtk": 4,
    "baseHp": 4,
    "effectText": "無效果。以較高裸值作為基礎怪獸。",
    "deckRefs": "決鬥×2／冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM001",
    "frameType": "LM"
  },
  "LM002": {
    "cardId": "LM002",
    "nameZh": "大屎塊",
    "type": "LM",
    "baseAtk": 3,
    "baseHp": 3,
    "effectText": "戰吼／首次強化階段：選擇 1 名「其他」存活我方怪物，永久 +2 ATK。不能指定自己；每張卡只成功發動一次。",
    "deckRefs": "決鬥×1／冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM002",
    "frameType": "LM"
  },
  "LM003": {
    "cardId": "LM003",
    "nameZh": "黑屎塊",
    "type": "LM",
    "baseAtk": 2,
    "baseHp": 3,
    "effectText": "投毒／首次削弱階段：連續造成 4 次「各 1 點」隨機傷害。每一擊都從當下仍存活的敵方怪中重新隨機目標；沒有敵人時剩餘傷害落空。每擊是獨立傷害事件，可各自觸發反擊。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM003",
    "frameType": "LM"
  },
  "LM004": {
    "cardId": "LM004",
    "nameZh": "白屎塊",
    "type": "LM",
    "baseAtk": 3,
    "baseHp": 3,
    "effectText": "護盾／首次防護階段：隨機 1 名存活我方怪物獲得護盾 2；可隨機到自己。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM004",
    "frameType": "LM"
  },
  "LM005": {
    "cardId": "LM005",
    "nameZh": "灰屎塊",
    "type": "LM",
    "baseAtk": 3,
    "baseHp": 3,
    "effectText": "計謀／首次削弱階段：選擇當前 ATK 最高的敵方怪物，使其永久 -2 ATK。若最高 ATK 並列，由控制者／AI依威脅選擇。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM005",
    "frameType": "LM"
  },
  "LM006": {
    "cardId": "LM006",
    "nameZh": "高速屎塊",
    "type": "LM",
    "baseAtk": 2,
    "baseHp": 4,
    "effectText": "每次它「成為合法攻擊目標」時，在該次攻擊真正結算前先抽 1。即使隨後被該攻擊擊殺，抽到的牌仍保留。非攻擊型傷害不觸發。",
    "deckRefs": "大屎×2",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM006",
    "frameType": "LM"
  },
  "LM007": {
    "cardId": "LM007",
    "nameZh": "高速屎彈",
    "type": "LM",
    "baseAtk": 4,
    "baseHp": 2,
    "effectText": "每次它即將對一個合法目標開始攻擊時，先抽 1，再結算攻擊。若正前方／特殊 targeting 找不到合法目標而揮空，則不抽。",
    "deckRefs": "大屎×2",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM007",
    "frameType": "LM"
  },
  "LM008": {
    "cardId": "LM008",
    "nameZh": "白魔法屎",
    "type": "LM",
    "baseAtk": 1,
    "baseHp": 5,
    "effectText": "首次防護階段：當時所有存活我方怪物（含自己）永久 +0/+2，並各獲護盾 1。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM008",
    "frameType": "LM"
  },
  "LM009": {
    "cardId": "LM009",
    "nameZh": "黑魔法屎",
    "type": "LM",
    "baseAtk": 3,
    "baseHp": 3,
    "effectText": "首次強化階段：當時所有存活我方怪物永久 +2 ATK。首次削弱階段：當時所有存活敵方怪物永久 -1 ATK。兩部分各自有一次性旗標；若卡在第二部分前死亡，未執行部分不發動。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM009",
    "frameType": "LM"
  },
  "LM010": {
    "cardId": "LM010",
    "nameZh": "灰魔法屎",
    "type": "LM",
    "baseAtk": 2,
    "baseHp": 4,
    "effectText": "每次被賦予 1 個「新的」正面／負面數值修正或狀態時抽 1。單一效果同時改多個數值（例如 +1/+1）只算 1 次。ATK/HP 修正、護盾、燃燒、冰凍算；普通攻擊傷害、純傷害、直接死亡、控制轉移本身不算。常駐光環首次套用可觸發一次，但持續重算不會每輪重觸發。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM010",
    "frameType": "LM"
  },
  "LM011": {
    "cardId": "LM011",
    "nameZh": "金針菇",
    "type": "LM",
    "baseAtk": 4,
    "baseHp": 2,
    "effectText": "覆寫一般攻擊 targeting：每次攻擊依「目標控制者的右 → 中 → 左」搜尋第一名存活敵人並攻擊；完全無敵人則揮空。",
    "deckRefs": "決鬥×1／冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM011",
    "frameType": "LM"
  },
  "LM012": {
    "cardId": "LM012",
    "nameZh": "火龍果",
    "type": "LM",
    "baseAtk": 2,
    "baseHp": 3,
    "effectText": "首次成功發動時，使當下所有存活敵方怪物獲得燃燒 1。燃燒可疊加、跨輪保留，於戰鬥階段開始按層數造成傷害；來源離場不移除既有燃燒。其精確所屬四階段在既有紀錄中未明文鎖死，實裝時應做成可配置 timing，而不要自行猜。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM012",
    "frameType": "LM"
  },
  "LM013": {
    "cardId": "LM013",
    "nameZh": "龍魔導屎",
    "type": "LM",
    "baseAtk": 3,
    "baseHp": 4,
    "effectText": "每次 Round End，隨機 1 名當時存活敵方怪物受到 1 點傷害。現行流程：先完成 ROUND SCORE，再處理此輪末傷害；因此不回溯本輪屎意。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM013",
    "frameType": "LM"
  },
  "LM014": {
    "cardId": "LM014",
    "nameZh": "屎萊姆",
    "type": "LM",
    "baseAtk": 2,
    "baseHp": 4,
    "effectText": "護盾／首次防護階段：選擇 1 名「其他」存活我方怪物，使其獲得護盾 2；不能選自己。",
    "deckRefs": "冠軍×2",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "LM014",
    "frameType": "LM"
  },
  "UM001": {
    "cardId": "UM001",
    "nameZh": "血便貴族",
    "type": "UM",
    "baseAtk": 3,
    "baseHp": 7,
    "effectText": "每次完成一次「對敵方怪物的有效攻擊」後，自身永久 +0/+1 HP。若沒有合法目標而揮空，不成長。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "UM001",
    "frameType": "UM"
  },
  "UM002": {
    "cardId": "UM002",
    "nameZh": "真紅眼屎黑龍",
    "type": "UM",
    "baseAtk": 7,
    "baseHp": 3,
    "effectText": "反擊：每次受到攻擊或傷害後若仍存活，立即攻擊正前方 1 次，無視當前階段。由反擊產生的攻擊不能再觸發反擊。",
    "deckRefs": "決鬥×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "UM002",
    "frameType": "UM"
  },
  "UM003": {
    "cardId": "UM003",
    "nameZh": "青眼屎白龍",
    "type": "UM",
    "baseAtk": 6,
    "baseHp": 4,
    "effectText": "每次 Round Start，自身永久 +1 ATK。每次 Round End，所有當時存活敵方怪物各受到 1 點傷害。現行流程：輪末傷害在 ROUND SCORE 後，因此不改寫本輪屎意。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "UM003",
    "frameType": "UM"
  },
  "UM004": {
    "cardId": "UM004",
    "nameZh": "巨屎兵",
    "type": "UM",
    "baseAtk": 4,
    "baseHp": 6,
    "effectText": "上位召喚後的首次防護階段，自身獲得護盾 2。遺言：死亡時選擇 1 名「其他」存活我方怪物永久 +2 ATK；若沒有其他我方怪物則落空。",
    "deckRefs": "冠軍×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "UM004",
    "frameType": "UM"
  },
  "SP001": {
    "cardId": "SP001",
    "nameZh": "被封印的屎首",
    "type": "SP",
    "baseAtk": 0,
    "baseHp": 0,
    "effectText": "不能正常打出；僅在手牌中作為特殊勝利素材。與 SP002、SP003 同時在手即立即觸發黑暗大法屎勝利。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "SP001",
    "frameType": "LM"
  },
  "SP002": {
    "cardId": "SP002",
    "nameZh": "被封印的屎身",
    "type": "SP",
    "baseAtk": 0,
    "baseHp": 0,
    "effectText": "不能正常打出；僅在手牌中作為特殊勝利素材。與 SP001、SP003 同時在手即立即觸發黑暗大法屎勝利。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "SP002",
    "frameType": "LM"
  },
  "SP003": {
    "cardId": "SP003",
    "nameZh": "被封印的屎足",
    "type": "SP",
    "baseAtk": 0,
    "baseHp": 0,
    "effectText": "不能正常打出；僅在手牌中作為特殊勝利素材。與 SP001、SP002 同時在手即立即觸發黑暗大法屎勝利。",
    "deckRefs": "大屎×1",
    "effectTags": [],
    "timings": [],
    "targeting": null,
    "triggerLimit": null,
    "artAsset": "SP003",
    "frameType": "LM"
  }
};
