import {catalog} from '../data/catalog.js';
import {imageURL,loadRuntimeImage} from './image-source.js';
import {raceOrder} from '../engine/quiz.js';
import {resultAssetId} from './appearance.js';
export function encodePublic(data){const payload=data.type==='quiz'?{type:'quiz',name:data.name,winners:data.winners,...(data.mode==='realistic'?{mode:'realistic'}:{})}:data.type==='ending'?{type:'ending',name:data.name,id:data.id}:{type:data.type,name:data.name,ids:data.ids};return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(payload))));}
export function decodePublic(hash){if(!hash.startsWith('#share='))return null;try{const text=hash.slice(7);if(text.length>12000)return null;const d=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(text),x=>x.charCodeAt(0))));if(!['quiz','ending','achievements','endings'].includes(d.type))return null;d.name=String(d.name||'旅人').slice(0,40);if(d.type==='quiz'){if(!d.winners&&d.scores){const max=Math.max(...Object.values(d.scores));d.winners=raceOrder.filter(id=>d.scores[id]===max);}if(!Array.isArray(d.winners)||!d.winners.length||d.winners.some(id=>!raceOrder.includes(id))||d.mode&&!['normal','realistic'].includes(d.mode))return null;d.winners=raceOrder.filter(id=>d.winners.includes(id));delete d.scores;}else if(d.type==='ending'){if(!catalog.endings[d.id])return null;}else{const list=d.type==='achievements'?catalog.achievements:catalog.endings;if(!Array.isArray(d.ids)||d.ids.some(id=>!list[id]))return null;d.ids=[...new Set(d.ids)];}return d;}catch{return null;}}
export function shareURL(data){const u=new URL(location.href);u.hash='share='+encodePublic(data);return u.href;}
export function shareText(data){if(data.type==='quiz')return `${data.name} 的隱藏身分：${data.winners.map(id=>catalog.races[id].name).join('、')}`;if(data.type==='ending')return `${data.name}｜${catalog.endings[data.id].name}\n${catalog.endings[data.id].text}`;const list=data.type==='achievements'?catalog.achievements:catalog.endings;return `化糞池王國｜${data.type==='achievements'?'成就':'結局'}收藏 ${data.ids.length}/${Object.keys(list).length}\n`+data.ids.map(id=>list[id].name).join('\n');}
export async function makeImage(data){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1000;ctx.font='30px sans-serif';const rows=[];for(const para of shareText(data).split('\n')){let line='';for(const c of para){if(ctx.measureText(line+c).width>840){rows.push(line);line=c;}else line+=c;}rows.push(line);}const winners=data.type==='quiz'?data.winners:[];const imageHeight=winners.length?290:0;canvas.height=Math.max(650,240+rows.length*48+imageHeight);ctx.fillStyle='#f3efe5';ctx.fillRect(0,0,1000,canvas.height);ctx.fillStyle='#233e31';ctx.fillRect(0,0,1000,110);ctx.fillStyle='#fffdf6';ctx.font='bold 36px sans-serif';ctx.fillText('你的隱藏身分  /  SHITOPIA',70,72);ctx.fillStyle='#28352e';ctx.font='30px sans-serif';rows.forEach((line,i)=>ctx.fillText(line,80,180+i*48));if(winners.length){const base=190+rows.length*48,slot=840/winners.length;for(const [i,id]of winners.entries()){const a=catalog.assets[resultAssetId(id,data.mode)],img=new Image();try{const loaded=await loadRuntimeImage(a.path,{priority:'high'});if(!loaded.ok)throw Error('Image unavailable');img.src=loaded.url;await img.decode();const scale=Math.min((slot-20)/img.naturalWidth,235/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,80+i*slot+(slot-w)/2,base+(235-h)/2,w,h);ctx.font='18px sans-serif';ctx.fillText(catalog.races[id].name,80+i*slot+slot/2-22,base+270);}catch{/* Text share remains valid if a result image is unavailable. */}}}ctx.fillStyle='#ad8146';ctx.font='20px sans-serif';ctx.fillText('一段從隱藏身分開始的旅程',80,canvas.height-45);return new Promise(resolve=>canvas.toBlob(resolve,'image/png'));}
export async function copyText(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return;}catch{}}const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();if(!ok)throw Error('瀏覽器不允許複製，請從分享欄位手動複製文字。');}
export function download(blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='shitopia-result.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
