import {el,text} from '../../ui/dom.js';
import {minigameAssets as assets} from '../assets.js';
import {art,gameButton,gameDialog} from '../shared/view.js';
import {sceneFrame} from '../../ui/scene-frame.js';
import {scenePanel} from '../../ui/scene-panel.js';
import {resolveCast} from '../../ui/scene-cast.js';
import {fitScene} from '../../ui/scene-layout.js';
import {dialogueHeader} from '../../ui/dialogue-header.js';
import {bindImageAreas,containedImageRect,sharedPaperLayout,LEFT_PAGE_SAFE_AREA,RIGHT_PAGE_SAFE_AREA,INVENTORY_CENTERS} from '../shared/image-layout.js';
import {hotspots,itemNames,noteLines,diaryPages,clueText,reportDialogue} from './data.js';
import {discoverClues,inventorySlots,inspect,clickItem,openItem,unlockDiary,availableInferences,toggleInference,toggleClue,reportInference,isHotspotInteractive} from './model.js';

export function mountPuzzle(host,{state:s,name='旅人',race='RAC-SHPB',demon='DMN-NONE',onChange=()=>{},onResult,onExit}){
 const a=assets.puzzle;let disposed=false,viewer=null,toastTimer,disposeImageLayout=null;
 const change=()=>{const added=discoverClues(s);onChange(s);if(added.length){const toast=host.querySelector('.puzzle-toast');toast.textContent='記錄了新線索！';clearTimeout(toastTimer);toastTimer=setTimeout(()=>{if(toast.isConnected)toast.textContent='';},2400);}renderInventory();refreshHotspots();};
 const room=el('div',{class:'puzzle-room'},art(a.room,'屎亡現場','puzzle-room-art'));
 room.append(gameButton('暫時離開',()=>{onChange(s);onExit();},{class:'puzzle-exit'}));
 const slots=el('div',{class:'inventory-slots'}),bar=el('div',{class:'puzzle-inventory'},art(a.inventoryBar,'六格道具欄','inventory-background'),slots);
 const dialogue=el('div',{class:'puzzle-dialogue','aria-live':'polite'}),toast=el('div',{class:'puzzle-toast',role:'status'});
 room.append(bar);
 const reportStage=el('div',{class:'puzzle-report-stage'});const root=el('section',{class:'formal-minigame puzzle plaid-sides'},room,toast,reportStage,dialogue);host.append(root);
 const fitRoom=()=>{if(!root.isConnected)return;const frame=reportStage.querySelector('.scene-frame');if(frame)fitScene(frame,document.querySelector('.footer'),host.closest('.shell'));const footer=document.querySelector('.footer');const bottom=footer?footer.getBoundingClientRect().top:innerHeight;root.style.setProperty('--puzzle-room-height',Math.max(250,bottom-root.getBoundingClientRect().top-16)+'px');};const roomObserver=new ResizeObserver(fitRoom);roomObserver.observe(host);window.addEventListener('resize',fitRoom);requestAnimationFrame(fitRoom);
 function refreshHotspots(){for(const button of room.querySelectorAll('[data-hotspot]')){button.disabled=!!s.dialogue||!isHotspotInteractive(button.dataset.hotspot,s,s.selected);}}
 const say=(message,speaker='player')=>{s.dialogue={speaker,text:message};onChange(s);drawDialogue();};
 function drawDialogue(){dialogue.replaceChildren();reportStage.replaceChildren();root.classList.toggle('reporting',!!s.report);room.hidden=!!s.report;refreshHotspots();if(!s.dialogue)return;const d=s.dialogue;const next=gameButton('繼續',()=>{s.dialogue=null;if(s.intro<2){s.intro++;if(s.intro===1)say('對了，我該把發現的線索寫下來。');else{onChange(s);drawDialogue();}}else if(s.report){s.report.step++;const r=s.report;const line=reportDialogue[r.result][r.step];if(line)say(line.text,line.speaker);else{s.report=null;onChange(s);drawDialogue();if(r.result!=='RETRY')onResult(r.result);}}else{onChange(s);drawDialogue();}},{class:'next'});const heading=dialogueHeader(d.speaker==='narrator'?null:d.speaker==='guard'?'見習屎衛':name,next);if(s.report){const parse=line=>({speaker:line.speaker==='player'?'NPC-001':line.speaker==='guard'?'NPC-007':null});const history=reportDialogue[s.report.result].slice(0,s.report.step).map(line=>({text:line})),cast=resolveCast(history,d,'F2.report',parse);reportStage.append(sceneFrame(scenePanel('dialogue',heading,text('div',d.text,'dialogue-text')),cast,{name,race,demon,location:'LOC-004'}));requestAnimationFrame(fitRoom);}else dialogue.append(heading,text('p',d.text));}
 for(const h of hotspots){const [x,y,r,b]=h.rect;room.append(gameButton('',()=>{if(s.dialogue||!isHotspotInteractive(h.id,s,s.selected))return;const message=inspect(s,h.id);change();if(message)say(message);},{class:'puzzle-hotspot',style:`left:${x}%;top:${y}%;width:${r-x}%;height:${b-y}%`,'aria-label':'調查'+h.name,'data-hotspot':h.id}));}
 function renderInventory(){slots.replaceChildren();const ids=inventorySlots(s);if(ids.length>6)throw Error('Puzzle inventory capacity exceeded');for(let i=0;i<6;i++){const id=ids[i];const btn=gameButton(id?art(a[id],itemNames[id]):'',()=>{if(!id||s.dialogue)return;clickItem(s,id);change();drawDialogue();if(s.viewer)showViewer();},{class:'inventory-slot'+(s.selected===id?' selected':''),'aria-label':id?itemNames[id]:'空道具格',disabled:!id,'data-item':id||''});slots.append(el('div',{class:'inventory-positioner',style:`left:${INVENTORY_CENTERS[i]*100}%;top:50%;`},btn));}}
 function closeViewer(){if(viewer?.open)viewer.close();s.viewer=null;onChange(s);}
 function notebook(){const left=el('div',{class:'notebook-page notebook-left'},s.clues.map(id=>gameButton(clueText[id-1],()=>{toggleClue(s,id);onChange(s);showViewer();},{class:'clue'+(s.crossed.includes(id)?' crossed':''),'data-clue':id}))),right=el('div',{class:'notebook-page notebook-right'});
  right.append(...availableInferences(s).map(r=>el('label',{class:'inference'},el('input',{type:'checkbox',checked:s.inference===r.id,disabled:s.inference!==null&&s.inference!==r.id,onChange:()=>{toggleInference(s,r.id);onChange(s);showViewer();},'data-inference':r.id}),text('span',r.text))));
  right.append(gameButton('向見習屎衛回報吧',()=>{const result=reportInference(s);if(!result)return;closeViewer();s.report={result,step:0};say(reportDialogue[result][0].text,reportDialogue[result][0].speaker);},{disabled:s.inference===null,class:'primary'}),gameButton('還是再看看吧',closeViewer));
  // Retired tools/evidence remain accessible without occupying live-use slots.
  const archive=el('details',{class:'evidence-archive'},el('summary',{},'已記錄的物件'),s.items.map(id=>gameButton(itemNames[id],()=>{s.viewer=openItem(s,id);change();showViewer();})));left.append(archive);
  left.tabIndex=right.tabIndex=0;left.setAttribute('aria-label','線索頁，可捲動');right.setAttribute('aria-label','推論頁，可捲動');const image=art(a.notebookOpen,'攤開的筆記本','notebook-art'),spread=el('div',{class:'notebook-spread'},image,left,right);disposeImageLayout=bindImageAreas(spread,image,[[left,LEFT_PAGE_SAFE_AREA],[right,RIGHT_PAGE_SAFE_AREA]]);return spread;
 }
 function paper(type){const fixed=el('div',{class:'paper-fixed'},noteLines[type].map(line=>el('div',{class:'paper-line'},line.split(/(【[^】]+】)/).map(part=>part.startsWith('【')?el('strong',{class:'note-red'},part.slice(1,-1)):part)))),content=el('div',{class:'paper-content'},fixed),image=art(a[type==='noteTop'?'noteTopBackground':'noteBottomBackground'],itemNames[type]),wrap=el('div',{class:'paper-view','data-paper':type},image,content);
  const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');const fit=()=>{const metrics={};for(const id of ['noteTop','noteBottom'])metrics[id]=noteLines[id].map(line=>line.split(/(【[^】]+】)/).reduce((sum,part)=>{ctx.font=`${part.startsWith('【')?'900':'400'} 100px "Microsoft JhengHei", sans-serif`;return sum+ctx.measureText(part.replace(/[【】]/g,'')).width/100;},0));const layout=sharedPaperLayout(containedImageRect({width:wrap.clientWidth,height:wrap.clientHeight},900,800),metrics),area=layout.areas[type];Object.assign(content.style,{left:area.left+'px',top:area.top+'px',width:area.width+'px',height:area.height+'px'});fixed.style.fontSize=layout.fontSize+'px';wrap.dataset.sharedFont=String(layout.fontSize);wrap.dataset.maxTop=String(layout.maxima.noteTop);wrap.dataset.maxBottom=String(layout.maxima.noteBottom);};disposeImageLayout=bindImageAreas(wrap,image,[],fit);document.fonts?.ready.then(()=>{if(wrap.isConnected)fit();});return wrap;}
 function showViewer(){if(disposed||!s.viewer)return;disposeImageLayout?.();disposeImageLayout=null;if(viewer){viewer.remove();viewer=null;}const v=s.viewer;let content;
  if(v.type==='notebook')content=notebook();else if(v.type==='noteTop'||v.type==='noteBottom')content=paper(v.type);
  else if(v.type==='password'){const input=el('input',{type:'text',inputmode:'numeric',maxlength:3,pattern:'[0-9]{3}','aria-label':'三位數密碼'});content=el('form',{class:'password-view',onSubmit:e=>{e.preventDefault();const message=unlockDiary(s,input.value);closeViewer();change();say(message);}},text('p','鎖上的日記，需要三位數的密碼。'),art(a.diary,itemNames.diary),input,el('button',{type:'submit'},'開鎖'));}
  else if(v.type==='diary')content=el('div',{class:'diary-view'},text('p',diaryPages[s.diaryPage]),el('div',{class:'row'},gameButton('上一頁',()=>{s.diaryPage--;onChange(s);showViewer();},{disabled:s.diaryPage===0}),gameButton('下一頁',()=>{s.diaryPage++;onChange(s);showViewer();},{disabled:s.diaryPage===4})));
  else content=el('div',{class:'object-view'},art(a[v.id||'story'],itemNames[v.id||'story']),text('p',v.text||itemNames[v.id]||''));
  const instance=gameDialog(v.type==='notebook'?'線索筆記本':v.type==='diary'?'屎者的日記':itemNames[v.id||v.type]||'物件',content,()=>{if(viewer===instance){disposeImageLayout?.();disposeImageLayout=null;viewer=null;s.viewer=null;onChange(s);}});viewer=instance;if(v.type==='notebook')instance.classList.add('notebook-viewer');if(['noteTop','noteBottom'].includes(v.type))instance.classList.add('paper-viewer');root.append(instance);instance.showModal();
 }
 renderInventory();refreshHotspots();if(s.intro===0&&!s.dialogue)say('先從現場開始調查吧。');else drawDialogue();if(s.viewer)showViewer();
 return ()=>{disposed=true;clearTimeout(toastTimer);disposeImageLayout?.();roomObserver.disconnect();window.removeEventListener('resize',fitRoom);viewer?.remove();root.remove();};
}
